apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: relay-pdb
  namespace: relay-system
  labels:
    app.kubernetes.io/part-of: grpc-relay
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: relay
