apiVersion: v1
kind: Service
metadata:
  name: relay
  namespace: relay-system
  labels:
    app: relay
    app.kubernetes.io/part-of: grpc-relay
spec:
  type: ClusterIP
  selector:
    app: relay
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: quic
      port: 50052
      targetPort: 50052
      protocol: UDP
    - name: health
      port: 8080
      targetPort: 8080
      protocol: TCP
